.semaphore/env-e2e.yml
e2e/config/config.exs
e2e/test/e2e/ui/login_test.exs

toil(e2e): update login tests

---

rbac/ce/Makefile
rbac/ce/config/runtime.exs
rbac/ce/lib/internal_api/guard.pb.ex
rbac/ce/lib/internal_api/organization.pb.ex
rbac/ce/lib/internal_api/projecthub.pb.ex
rbac/ce/lib/internal_api/rbac.pb.ex
rbac/ce/lib/internal_api/user.pb.ex
rbac/ce/lib/rbac/events.ex
rbac/ce/lib/rbac/grpc_servers/rbac_server.ex
rbac/ce/test/rbac/events_test.exs
rbac/ce/test/rbac/grpc_servers/rbac_server_test.exs
rbac/ce/test/support/test_consumer.ex

We're not sending authentication events when the user role changes. Because of this cache invalidation in front does not work properly. 
- Closes 
- Related to

fix(rbac): emit change events when roles change

---

front/assets/js/agents/components/activity_monitor.tsx
front/lib/front_web/templates/layout/_page_header.html.eex
front/lib/front_web/templates/layout/organization.html.eex

Replacing feedback button with link to agents page.
- Closes 
- Related to

toil(front): header changes

---

front/assets/js/project_onboarding/new/pages/workflow_setup/project_environment.tsx
front/assets/js/project_onboarding/new/pages/workflow_setup/starter_workflow_template.tsx

Preselect an agent type and a "Fan-in" workflow template in project onboarding
- Closes 
- Related to

fix(front): preselect agent types and templates available on project onboarding

---

front/assets/js/git_integration/pages/integration_page.tsx
front/assets/js/git_integration/pages/integration_page/bitbucket.tsx
front/assets/js/git_integration/pages/integration_page/gitlab.tsx
front/assets/js/git_integration/stores/config.ts
front/lib/front/github_app.ex
front/lib/front_web/views/git_integration_view.ex

cherry pick of: e01e71c9595162ae1f753799b30fc88e098195b9
- Closes 
- Related to

fix(front): github app url nil if cached value does not contain field

---

guard/.gitignore
guard/Makefile
guard/config/runtime.exs
guard/docker-compose.yml
guard/lib/guard/front_repo/organization.ex
guard/priv/repo/migrations/20240520135121_add_audit_trigger.exs
guard/test/guard/front_repo/organization_test.exs
guard/test/guard/grpc_servers/organization_server_test.exs
guard/test/guard/store/organization_test.exs

cherry pick of this PR https://github.com/semaphoreio/semaphore/pull/10

toil(guard): update reserved usernames

---

rbac/ce/Makefile
rbac/ce/config/runtime.exs
rbac/ce/lib/internal_api/guard.pb.ex
rbac/ce/lib/internal_api/organization.pb.ex
rbac/ce/lib/internal_api/projecthub.pb.ex
rbac/ce/lib/internal_api/rbac.pb.ex
rbac/ce/lib/internal_api/user.pb.ex
rbac/ce/lib/rbac/events.ex
rbac/ce/lib/rbac/grpc_servers/rbac_server.ex
rbac/ce/test/rbac/events_test.exs
rbac/ce/test/rbac/grpc_servers/rbac_server_test.exs
rbac/ce/test/support/test_consumer.ex

cherry pick of: 5d15f7ad04d16985b1fa78dfec0784ac610045de
- Closes 
- Related to

fix(rbac): emit change events when roles change (#19)

---

front/assets/js/agents/components/activity_monitor.tsx
front/lib/front_web/templates/layout/_page_header.html.eex
front/lib/front_web/templates/layout/organization.html.eex

cherry pick of: 12bcfca97fb2ca69e78331c2995c1217c9bd6b75
- Closes 
- Related to

toil(front): header changes (#21)

---

front/assets/js/project_onboarding/new/pages/workflow_setup/project_environment.tsx
front/assets/js/project_onboarding/new/pages/workflow_setup/starter_workflow_template.tsx

cherry pick of: 43e642626439f2fe5ddecfe629c5bf2625ebe5f3
functionality to change)
- Closes 
- Related to 
- Closes 
- Related to

fix(front):  preselect agent types and templates available on project onboarding

---

front/assets/js/git_integration/pages/home_page.tsx
front/assets/js/git_integration/pages/integration_page/bitbucket.tsx
front/assets/js/git_integration/pages/integration_page/gitlab.tsx
front/assets/js/git_integration/utils.ts
front/lib/front/telemetry.ex
front/lib/front_web/controllers/git_integration_controller.ex
guard/lib/guard/instance_config/github_app.ex

Cherry pick of git integrations fixed for new release
- Closes 
- Related to

fix: set git integrations screens sorting and integration updates (#23)

---

front/lib/front_web/controllers/organization_onboarding_controller.ex

Removed an unnecessary dot from the URL constructor for the wait page during the organization creation process.

fix(front): remove unnecessary dot from wait url

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/toil.md
.github/pull_request_template.md
GOVERNANCE.md
README.md
ROADMAP.md

- Several cosmetic adjustments to issue templates and main readme
- Bigger update of the placeholder ROADMAP.md
- Simplified PR template

toil(repo): repository settings update

---

ee/rbac/.gitignore
ee/rbac/lib/rbac/api/project.ex
ee/rbac/lib/rbac/api/repository.ex
ee/rbac/lib/rbac/events/authorization.ex
ee/rbac/lib/rbac/events/user_created.ex
ee/rbac/lib/rbac/events/user_joined_organization.ex
ee/rbac/lib/rbac/events/user_left_organization.ex
ee/rbac/lib/rbac/events/user_updated.ex
ee/rbac/lib/rbac/okta/integrations.ex
ee/rbac/lib/rbac/repo/okta_integrations.ex
ee/rbac/lib/rbac/store/postgres.ex
ee/rbac/lib/rbac/store/user_permissions.ex
ee/rbac/priv/repo/migrations/20250227121254_add_jit_provisioning_field.exs
ee/rbac/test/rbac/collaborators_refresher_test.exs
ee/rbac/test/rbac/grpc_servers/groups_server_test.exs
ee/rbac/test/rbac/grpc_servers/okta_server_test.exs
ee/rbac/test/rbac/grpc_servers/rbac_server_test.exs
ee/rbac/test/rbac/okta/scim/api_test.exs
ee/rbac/test/rbac/services/project_creator_test.exs
ee/rbac/test/rbac/services/project_destroyer_test.exs
ee/rbac/test/support/factories.ex
ee/rbac/test/support/test_consumer.ex
guard/priv/repo/migrations/202502271212544_add_jit_provisioning_field.exs

We are working on a feature to support SAML JIT Provisioning. In order to parallelize further work, I've created this PR to perform necessary DB Migrations.
- Related to: https://github.com/renderedtext/tasks/issues/7566

feat(guard): extend saml integration with jit provisiooning field

---

github_hooks/Makefile
github_hooks/lib/semaphore/github_app/hook.rb

- Refactored queries to use parameterized statements for `installation_id`
- Ensured consistent JSON formatting for `repositories` using `quote`
- Closes: 
- Related to:

fix(github_app): improve repository updates handling

---

github_hooks/app/controllers/projects_controller.rb
github_hooks/config/app/development.rb
github_hooks/config/app/production.rb
github_hooks/config/app/test.rb
github_hooks/config/config.yml
github_hooks/lib/semaphore/github_app/credentials.rb
github_hooks/lib/semaphore/github_app/hook.rb
github_hooks/spec/controllers/projects_controller_spec.rb
github_hooks/spec/lib/semaphore/github_app/hook_spec.rb

Verify signatures on GitHub App webhooks.
- Related to: https://github.com/renderedtext/tasks/issues/7572

fix(github_hooks): improve GitHub App webhook handling

---

Makefile

Cherry pick of https://github.com/semaphoreio/semaphore/commit/57b3456ed3ac49459a10003da3a6687ca14b2578

fix: ignore license check for internal libraries (#104)

---

front/assets/js/app.js
front/assets/js/people/add_people/config.ts
front/assets/js/people/add_people/index.tsx
front/assets/js/people/add_people/types.ts
front/assets/js/people/sync_people/index.tsx
front/lib/front_web/controllers/people_controller.ex
front/lib/front_web/templates/people/organization.html.eex
front/lib/front_web/views/people_view.ex
front/test/support/stubs/rbac.ex

- Added missing `sync` button to refresh collaborators on people page.
- Refactored adding people component for clarity

fix(front): add missing sync button to people page

---

.github/CODEOWNERS

Add pedro as codeowner of guard and rbac

toild(rbac): Add pedro as codeowner of rbac and guard

---

ee/rbac/lib/internal_api/rbac.pb.ex
ee/rbac/lib/rbac/front_repo/user.ex
ee/rbac/lib/rbac/grpc_servers/rbac_server.ex
ee/rbac/lib/rbac/okta/saml/api.ex
ee/rbac/lib/rbac/okta/saml/jit_provisioner/add_user.ex
ee/rbac/lib/rbac/okta/saml/payload_parser.ex
ee/rbac/lib/rbac/repo/saml_jit_user.ex
ee/rbac/lib/rbac/repo/subject_role_binding.ex
ee/rbac/priv/repo/migrations/20250903231134_create_saml_jit_users.exs
ee/rbac/priv/repo/migrations/20250903233404_add_saml_jit_to_role_binding_type_enum.exs
ee/rbac/priv/repo/migrations/20250903233405_add_saml_jit_to_role_binding_type_enum.exs
ee/rbac/test/rbac/okta/saml/api_test.exs
ee/rbac/test/rbac/okta/saml/payload_parser_test.exs
ee/rbac/test/support/okta/saml/payload_builder.ex
front/lib/front_web/views/people_view.ex
front/lib/internal_api/instance_config.pb.ex
front/lib/internal_api/rbac.pb.ex
guard/lib/guard/front_repo/user.ex
guard/lib/internal_api/instance_config.pb.ex
guard/lib/internal_api/rbac.pb.ex
guard/priv/repo/migrations/202509032311344_create_saml_jit_users.exs
guard/priv/repo/migrations/202509032334044_add_saml_jit_to_role_binding_type_enum.exs
guard/priv/repo/migrations/202509032334045_add_saml_jit_to_role_binding_type_enum.exs

I have updated our saml login procedure. Now, if the user does not exist already, and the organization has JIT provisioning enabled within it's SAML integration, the user will be created on the spot.
https://github.com/renderedtext/tasks/issues/7566

feat(rbac): saml jit provisioning

---

.semaphore/daily-builds.yml
.semaphore/env-create.yml
.semaphore/env-e2e.yml
.semaphore/generate-helm-chart.yml
.semaphore/semaphore.yml
ee/gofer/helm/templates/dpl.yaml
ee/pre_flight_checks/helm/templates/deployment.yml
ee/pre_flight_checks/helm/templates/service.yml
ee/velocity/helm/templates/api.yaml
ee/velocity/helm/templates/emitter.yaml
ee/velocity/helm/templates/metric-aggregator.yaml
ee/velocity/helm/templates/summary-worker.yaml
ee/velocity/helm/templates/worker.yaml
ephemeral_environment/Makefile
ephemeral_environment/scripts/install.sh
ephemeral_environment/scripts/vm-install.sh
helm-chart/Chart.yaml.in
helm-chart/Dockerfile
helm-chart/Makefile
helm-chart/scripts/prepare-chart.sh
helm-chart/values.yaml.in

Introduces a new global value to distinguish between CE and EE versions. Updates promotions to enable deployment and testing for both versions.
For more details, see: https://github.com/renderedtext/project-tasks/issues/2271

feat(helm): add edition global value

---

ee/rbac/lib/rbac/okta/idp_group_mapping.ex
ee/rbac/lib/rbac/repo/idp_group_mapping.ex
ee/rbac/test/rbac/grpc_servers/okta_server_test.exs

We should be able to save role mappings without group mappings
https://github.com/renderedtext/tasks/issues/7617

fix(front): group mappings can be saved empty

---

front/helm/templates/job-page.yaml
front/helm/templates/project-page.yaml
front/helm/templates/ui-cache-reactor.yaml
helm-chart/templates/configmaps/features.yaml

Enables velocity in EE.
For more details, see: [project task](https://github.com/renderedtext/project-tasks/issues/2276)

feat(velocity): enable velocity in ee

---

.semaphore/generate-helm-chart.yml
ee/audit/config/runtime.exs
ee/audit/helm/.gitignore
ee/audit/helm/.helmignore
ee/audit/helm/Chart.yaml.in
ee/audit/helm/templates/deployment.yaml
ee/audit/helm/templates/service.yaml
ee/audit/helm/values.yaml
front/helm/templates/job-page.yaml
front/helm/templates/project-page.yaml
front/helm/templates/ui-cache-reactor.yaml
helm-chart/Chart.yaml.in
helm-chart/scripts/prepare-chart.sh
helm-chart/templates/configmaps/features.yaml

Adds audit in EE.
For more details, see: [project task](https://github.com/renderedtext/project-tasks/issues/2273).

feat(audit): add audit to ee

---

front/assets/js/time_ago.js
front/lib/front_web/templates/roles/_new_role_btn.html.eex

The button that leads to the New Role page should send get, not post request
https://github.com/renderedtext/tasks/issues/7659

fix(front): send get request instead of post

---

.semaphore/semaphore.yml

update release change_in in semaphore.yml to 1.1.x

refactor: update release change_in in semaphore.yml

---

front/lib/front_web/controllers/people_controller.ex

As described in this comment, We update the success message for Sync.
https://github.com/semaphoreio/semaphore/issues/86#issuecomment-2751029311

refactor(front): update sync-success-message

---

front/lib/front_web/templates/account/show.html.eex
front/lib/front_web/templates/people/show.html.eex

Cherry pick of https://github.com/semaphoreio/semaphore/commit/0698fbfdc183583b57ed4460dfc86e07face1240

fix(front): Git Profiles page format (#172)

---

front/lib/front_web/controllers/people_controller.ex

Cherry pick of [refactor(front): update sync-success-message](https://github.com/semaphoreio/semaphore/commit/a2a0e228ae46edbaef97ef62cbfd69dedd336b28)

refactor(front): update sync-success-message (#167)

---

.semaphore/semaphore.yml

- add ignore pipeline_file in change_in from Docs semaphore.yml
~- [ ] I have tested this change~
~- [ ] This change requires documentation update~

fix(docs): fix change_in in semaphore.yml

---

bootstrapper/cmd/init_org.go
bootstrapper/helm/templates/init-org-job.yml
bootstrapper/pkg/installation/installation.go
bootstrapper/pkg/telemetry/telemetry.go
bootstrapper/pkg/telemetry/telemetry_test.go

Cherry pick of feat(boostrapper): add installed telemetry request in boostrapper (#184)

feat(boostrapper): add installed telemetry request in boostrapper (#184)

---

docs/versioned_docs/version-CE/getting-started/install-aws-ec2.md
docs/versioned_docs/version-CE/getting-started/install-eks.md
docs/versioned_docs/version-CE/getting-started/install-gcompute.md
docs/versioned_docs/version-CE/getting-started/install-gke.md
docs/versioned_docs/version-CE/getting-started/install-ubuntu.md

Fix upgrade instructions to use the command that will always work.

docs: fix upgrade instructions

---

front/lib/front_web/templates/deployments/_item.html.eex
front/lib/front_web/views/deployments_view.ex

https://github.com/renderedtext/tasks/issues/7752

fix(front): display 'delete_user' on deployments

---

docs/docs/getting-started/changelog.md
docs/docs/reference/os-ubuntu-images/ubuntu-2004-image.md
docs/docs/reference/os-ubuntu-images/ubuntu-2204-arm-image.md
docs/docs/reference/os-ubuntu-images/ubuntu-2204-image.md
docs/docs/reference/os-ubuntu-images/ubuntu-2404-image.md

As forked [PR](https://github.com/semaphoreio/semaphore/pull/201) is blocked by workflow not running this is a direct push to unblock @d-stefanovic

docs: Ubuntu image changelog April 7

---

ee/rbac/lib/rbac/role_management.ex
ee/rbac/test/rbac/grpc_servers/rbac_server_test.exs
ee/rbac/test/rbac/role_management_test.exs

(https://github.com/renderedtext/tasks/issues/7794)

fix(rbac): if role does not exist anymore, treat it as no one has it

---

front/assets/js/workflow_editor/models/agent.js
front/config/runtime.exs
front/helm/templates/job-page.yaml
front/helm/templates/project-page.yaml
front/helm/templates/ui-cache-reactor.yaml
front/lib/front.ex
front/lib/front_web/templates/project/edit_workflow.html.eex
front/lib/front_web/templates/project_onboarding/setup.html.eex
front/lib/front_web/templates/workflow/edit.html.eex

Cherry picked changes from https://github.com/semaphoreio/semaphore/pull/191

fix(front): fix setting default agent type, image in wf editor (#191)

---

docs/docs/getting-started/changelog.md

Added iOS simulator 18.2, 18.3.1

docs: update changelog

---

docs/docs/reference/os-ubuntu-images/ubuntu-2204-image.md
docs/docs/reference/os-ubuntu-images/ubuntu-2404-image.md

- Update description page for Ubuntu 22.04 and 24.04 images

docs: Update Ubuntu images docs

---

guard/lib/guard/events/organization_restored.ex
guard/lib/guard/grpc_servers/organization_server.ex
guard/lib/guard/store/organization.ex
guard/lib/internal_api/okta.pb.ex
guard/lib/internal_api/organization.pb.ex
guard/lib/internal_api/projecthub.pb.ex
guard/test/guard/grpc_servers/organization_server_test.exs
guard/test/guard/store/organization_test.exs

- Added organization restore service
- Add soft_delete param filters in describe, describe_many and list
- Added tests for the new service and for the changed ones

feat(guard): add organization restore service

---

ee/rbac/lib/rbac/grpc_servers/groups_server.ex
ee/rbac/lib/rbac/store/group.ex
ee/rbac/test/rbac/grpc_servers/groups_server_test.exs
ee/rbac/test/rbac/store/group_test.exs
ee/rbac/test/support/factories/group_factory.ex

Group name should be unique per organization
https://github.com/renderedtext/tasks/issues/7876

fix(group): make group name unique

---

github_hooks/Gemfile
github_hooks/Gemfile.lock

fix(github_hooks): CVE-2025-43857

---

ee/delivery-hub/pkg/grpc/actions/create_event_source.go
ee/delivery-hub/pkg/public/org_middleware.go
ee/delivery-hub/pkg/public/server.go
ee/delivery-hub/pkg/public/server_test.go

- Add semaphore event source handling
- Added some todos for creating secret and notification
- Updated organization middleware

feat(delivery-hub): add semaphore event source handling

---

front/assets/js/workflow_list.js

feat(front): Whenever changing workflows page, update the state

---

ee/delivery-hub/db/migrations/20250512212918_add-stage-event-headers-column.down.sql
ee/delivery-hub/db/migrations/20250512212918_add-stage-event-headers-column.up.sql
ee/delivery-hub/db/structure.sql
ee/delivery-hub/pkg/grpc/actions/create_stage.go
ee/delivery-hub/pkg/grpc/actions/create_stage_test.go
ee/delivery-hub/pkg/grpc/actions/list_tags_test.go
ee/delivery-hub/pkg/grpc/actions/update_tag_state_test.go
ee/delivery-hub/pkg/models/event.go
ee/delivery-hub/pkg/models/stage_connection.go
ee/delivery-hub/pkg/models/stage_connection_test.go
ee/delivery-hub/pkg/models/stage_execution_test.go
ee/delivery-hub/pkg/protos/delivery/delivery.pb.go
ee/delivery-hub/pkg/public/server.go
ee/delivery-hub/pkg/resolver/resolver_test.go
ee/delivery-hub/pkg/workers/pending_events_worker_test.go
ee/delivery-hub/pkg/workers/pending_executions_worker_test.go
ee/delivery-hub/pkg/workers/pipeline_done_consumer.go
ee/delivery-hub/pkg/workers/pipeline_done_consumer_test.go
ee/delivery-hub/test/support/support.go

- Add header Filter type for conditions
- Header names should be case sensitive
- Add Header function to expression parser because of dashed header names

feat(delivery-hub): add header filter type

---

docs/docs/using-semaphore/optimization/container-registry.md

- docs: update supported mysql container versions

docs: update supported mysql container versions

---

helm-chart/values.yaml.in

Updates toolbox to v1.25.0, which embeds new test results CLI.

toil: update toolbox to v1.25.0

---

front/assets/js/report/index.tsx
front/lib/front/breadcrumbs/project.ex
front/lib/front_web/controllers/report_controller.ex
front/lib/front_web/router.ex
front/lib/front_web/templates/layout/project.html.eex
front/priv/storage/reports/project_report.md
front/test/browser/report_page_test.exs
front/test/support/stubs/project.ex

https://github.com/semaphoreio/semaphore/issues/310

feat(front): add project level reports

---

front/lib/front/branch_page/model.ex
front/lib/front/models/secret_updater.ex
front/lib/front/models/support_request.ex
front/lib/front/project_settings/deletion_validator.ex
front/lib/front_web/controllers/artifacts_controller.ex
front/lib/front_web/controllers/notifications_controller.ex
front/lib/front_web/controllers/organization_okta_controller.ex
front/lib/front_web/controllers/project_pfc_controller.ex
front/lib/front_web/controllers/project_settings/secrets_controller.ex
front/lib/front_web/controllers/secrets_controller.ex
front/lib/front_web/controllers/support_controller.ex
front/test/front_web/controllers/roles_controller_test.exs
front/test/support/stubs/scheduler.ex

While working on https://github.com/renderedtext/project-tasks/issues/2405, I could not get a green build due to linting errors. This PR fixes credo lint errors.

toil(front): Refactor all the front lint suggestions

---

front/assets/js/workflow_list.js
front/lib/front_web/templates/branch/_filters.html.eex
front/lib/front_web/templates/branch/member.html.eex

https://github.com/renderedtext/project-tasks/issues/2410
Add an error message if filtering options are not valid
https://github.com/user-attachments/assets/a868fb73-07ac-4bc1-a1d5-f21643d50434

fix(front): wf filtering add error msg

---

front/lib/front_web/views/shared_helpers.ex

Another place missing GitLab mapping

Add function pattern matching for gitlab

---

self_hosted_hub/cmd/server/main.go
self_hosted_hub/pkg/logging/logging.go
self_hosted_hub/pkg/publicapi/logging.go
self_hosted_hub/pkg/publicapi/server.go

Makes setting up logging level possible trough env var
default log level info
custom logging middleware using logrus that logs all requests on debug level

chore: set json logging format and reduce log priority of large messages

---

docs/default.conf
docs/docs/using-semaphore/okta.md
docs/versioned_docs/version-EE/using-semaphore/okta.md

Add info note about Okta integration to the Cloud and EE versions
Fixes: https://github.com/semaphoreio/semaphore/issues/383

docs: add info note about Okta usage

---

security-toolbox/docker
security-toolbox/policies/docker/trivy_image.rb
security-toolbox/policies/docker/trivy_table_output.rb

This PR enables passing a list of scanners to be used for policy checks.

feat(security-toolbox): allow scanners to be configured

---

.semaphore/semaphore.yml
e2e/scripts/test-setup.sh
e2e/test/e2e/ui/git_integrations_test.exs
public-api-gateway/helm/templates/dpl.yaml

This PR includes:
- Cherry-picked changes from #432
- Update of default branch for `v1.4.x`

toil: cherry pick #432, update default branch

---

guard/templates/blocked.html.eex

https://github.com/renderedtext/tasks/issues/8283

toil(guard): Change abuseprevention address in guard

---

LOCAL-DEVELOPMENT.md
helm-chart/templates/NOTES.txt

The place of storing credentials was changed in this PR https://github.com/semaphoreio/semaphore/pull/338

Update get credentials script

---

public-api/v2/helm/values.yaml

During bootup, service is often killed by OOMKiller

config(public-api): increase memory resources

---

front/assets/js/test_results/util/interactive_pipeline_tree.tsx
front/lib/front_web/templates/test_results/member/pipeline.html.eex

Render the pipeline name as a plain text.

toil(front): treat ppl name as a plain txt

---

github_hooks/Gemfile
github_hooks/Gemfile.lock

Address https://github.com/advisories/GHSA-353f-x4gh-cqq8 in github_hooks service.

fix(github_hooks): GHSA-353f-x4gh-cqq8

---

front/assets/js/blocked.js
front/assets/js/template_picker.js
front/assets/js/workflow_editor/components/commit_panel.js

https://github.com/renderedtext/project-tasks/issues/2660

fix(front): URL encode branch name in case in contains '&' or '?' character

---

front/lib/front_web/plugs/content_security_policy.ex

https://github.com/renderedtext/project-tasks/issues/2654

fix(front): Specify `form_action: self` directive

---

front/assets/js/report/index.tsx

https://github.com/renderedtext/project-tasks/issues/2650

feat(front): allow some HTML tags in markdown reports

---

front/lib/front_web/plugs/content_security_policy.ex

Fix for [this issue](https://github.com/renderedtext/tasks/issues/8338).

fix(front): enable domain in form action

---

front/lib/front/rbac/role_management.ex

https://github.com/renderedtext/tasks/issues/8343

fix(front): Extend timeout for rbac api calls

---

front/lib/front_web/plugs/content_security_policy.ex

When implementing security restrictions, we created an issue with connectingthe  semaphore and GH/BB accounts. This should fix it
https://github.com/renderedtext/tasks/issues/8368

fix(front): form action restrictions

---

ee/rbac/lib/rbac/okta/saml/api.ex

fix(rbac_ee): add debug logs

---

front/assets/js/app.js
front/assets/js/billing/app.tsx
front/assets/js/flaky_tests/app.tsx
front/assets/js/flaky_tests/components/actions.tsx
front/assets/js/insights/components/insights.tsx
front/assets/package-lock.json
front/assets/package.json
front/config/config.exs
front/config/runtime.exs
front/lib/front_web/plugs/assign_user_info.ex
front/lib/front_web/plugs/content_security_policy.ex
front/lib/front_web/templates/layout/_scripts.html.eex
front/lib/front_web/views/layout_view.ex
front/test/browser/people_test.exs

Replace the current Userpilot tracker with Posthog.

feat(front): replace userpilot with posthog

---

guard/templates/login.html.eex
guard/templates/signup.html.eex

Fix the parameter passing to the guard HTML templates

fix(guard): fix template assigns

---

front/assets/js/tasks/history_page.js
front/lib/front_web/controllers/project_controller.ex
front/test/front_web/controllers/project_controller_test.exs

Lists tags in the task run history filter

fix: filter based on tags on top of branch names

---

front/assets/js/tasks/history_page.js
front/lib/front_web/controllers/project_controller.ex
front/test/front_web/controllers/project_controller_test.exs

cherry-pick of https://github.com/semaphoreio/semaphore/pull/611

chore: update change_in directives (#604)

---

front/assets/js/service_accounts/components/CreateServiceAccount.tsx
front/assets/js/service_accounts/components/EditServiceAccount.tsx

fix(front): fix overflowing service account role selection dropdown
