semaphoreio/semaphore

- Makefile
Image signing for GCR is failing due to [this issue](https://semaphore.semaphoreci.com/jobs/ce075e89-8a72-4923-992c-6604547b8ad9). This fixes it.
> fix: use proper digest index for GCR push

- projecthub/helm/values.yaml
Cherry picking [14cd5973](https://github.com/semaphoreio/semaphore/commit/14cd5973a3c6c85b2157728608b0352829c1fa3e) into the release branch.
> fix(projecthub): increase dbPoolSize (#8)

- repohub/go.mod
- repohub/go.sum
- repohub/test/support/fake_repository_integrator_service.go
Moves from github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt/v5, addressing [dependabot#16](https://github.com/semaphoreio/semaphore/security/dependabot/16).
> fix(repohub): migrate to github.com/golang-jwt/jwt/v5

- ee/audit/lib/audit/application.ex
- ee/audit/lib/audit/feature_provider_invalidator_worker.ex
- ee/audit/lib/internal_api/feature.pb.ex
- front/config/config.exs
- front/config/test.exs
- front/lib/front/application.ex
- front/lib/front/feature_hub_provider.ex
- front/lib/front/feature_provider_invalidator_worker.ex
- github_notifier/lib/github_notifier/application.ex
- github_notifier/lib/github_notifier/feature_provider_invalidator_worker.ex
- projecthub/lib/projecthub/application.ex
- projecthub/lib/projecthub/feature_provider_invalidator_worker.ex
- secrethub/lib/secrethub/application.ex
- secrethub/lib/secrethub/feature_provider_invalidator_worker.ex
Update applications to refresh cached feature flags / machines when they are updated. This was already the case in zebra and guard, and now we add it to all the other applications consuming feature flags too.
Ref: https://github.com/renderedtext/project-tasks/issues/2202
> feat: use feature provider invalidator worker

- front/assets/js/flaky_tests/components/notification.tsx
Constructing a list of branches in flaky test notifications breaks when no branches are specified.
> fix(front): constructing flaky test branches list

- Makefile
- Ignore internal libraries for license check to avoid breaking the services and keep the green build.
- Ignoring only libraries that we know that have valid license or the ones that are internal to the monorepo.
> fix: ignore license check for internal libraries

- .semaphore/generate-helm-chart.yml
- Makefile
- self_hosted_hub/pkg/publicapi/server.go
When building the Helm chart, we do not need to build/push images that already exist. By skipping that, we can save up to ~1h of build time (if we sum up all the durations in all the build/push jobs) and ~10min of waiting (the maximum duration  is ~10min, for the github_hooks application) on the "Generate Helm chart" promotion.
Ref: https://github.com/renderedtext/project-tasks/issues/2269
> fix: skip build/push image if it already exists

- front/lib/front_web/controllers/notifications_controller.ex
- front/lib/front_web/controllers/people_controller.ex
- front/lib/front_web/controllers/project_settings_controller.ex
- front/lib/front_web/controllers/self_hosted_agent_controller.ex
Related Task: https://github.com/semaphoreio/semaphore/issues/35
- Some Grpc error messages are being URL encoded to [an update in its grpc library ](https://github.com/elixir-grpc/grpc/pull/271)
- Added Uri encode in grpc responses to ensure it will be decoded. If not, it will keep the same.
> fix(front): decode URL encoded grpc error messages

- guard/lib/guard/front_repo.ex
- guard/lib/guard/store/user.ex
A month back we removed deprecated tables for Quotas and UserRefs. In Guard, there was still a reference to this entity, and this PR removed it.
> Remove references to Quota which does no longer exist

- bootstrapper/cmd/gen_secrets.go
- bootstrapper/cmd/gen_secrets_test.go
- bootstrapper/helm/templates/gen-secrets-job.yml
- bootstrapper/pkg/kubernetes/kubernetes.go
- ee/gofer/helm/templates/dpl.yaml
- helm-chart/templates/configmaps/features.yaml
- helm-chart/templates/emissary-ingress/mappings.yaml
- helm-chart/templates/secrets.tpl
- helm-chart/values.yaml.in
- plumber/ppl/helm/templates/plumber-dpl.yml
- secrethub/helm/templates/dpl.yaml
- Enabled `gofer` in EE, including promotions and deployment targets.
- Updated `secrethub` to use vault and OIDC keys, and enabled the OIDC server in EE.
- Modified `bootstrapper` to generate vault and OIDC keys for EE.
For more details, see: [project task](https://github.com/renderedtext/project-tasks/issues/2272)
> feat(gofer, secrethub): enable gofer and oidc in ee

- ee/rbac/lib/rbac/grpc_servers/rbac_server.ex
- ee/rbac/lib/rbac/okta/saml/jit_provisioner/add_user.ex
- ee/rbac/lib/rbac/repo/subject_role_binding.ex
Roles that have been assigned through saml jit provisioning should be managed later on manually. Hence we have to mark them as :manually_assigned
https://github.com/renderedtext/tasks/issues/7653
> fix(rbaac): SAML assigned roles can be managed manually

- front/workflow_templates/ce_new/templates/simple.yml
Related Issue: https://github.com/semaphoreio/semaphore/issues/133
- Added missing simple.yml template file for CE
- This template has changeable os_image and machine type
- It was missing when Clicking on Design from Scratch for the workflow builder.
- It fixes an error 500 in CE
> fix(front): add simple.yml to ce_new

- guard/templates/logout.html.eex
- keycloak/image/themes/semaphore/login/login.ftl
- When we changed to the signup and login Page, I missed the CE Login page and the Logout
- This PR remove the gradients
> refactor: replace gradient to fixed color in logout and CE login page

- front/assets/css/app-semaphore.css
- front/assets/css/app.css
app-semaphore.css is not loaded. What was loaded is app.css and app-semaphore-min.css (generated).
So, I just changed the select-none class that was added to app.css.
> fix(front): move select-none to app.css

- front/assets/js/time_ago.js
- front/lib/front/utils.ex
- front/test/front/utils_test.exs
As discussed with @AleksandarCole, we introduced a new rule to the timestamps:
- If the time difference is less than 1 hour, it will be displayed as a relative time (e.g., "5 minutes ago").
- If the time difference is between 1 hour and 3 days, it will now follow the format: {weekday} #{suffixed_day} {month} {year} at HH:mm (e.g., "Tue 5th Mar 2024 at 14:30").
- If the time difference is greater than 3 days, it will follow the existing full date format (e.g., "on Tue 5th Mar 2024").
> fix(front: refactor timestamps format to up to 1 hour

- front/assets/js/time_ago.js
- front/lib/front/utils.ex
- front/test/front/utils_test.exs
Cherry pick of https://github.com/semaphoreio/semaphore/commit/67143e04251514d8f6475adbcd360067f831a757
> fix(front): refactor timestamps format to up to 1 hour (#168)

- bootstrapper/cmd/init_org.go
- bootstrapper/helm/templates/init-org-job.yml
- bootstrapper/pkg/installation/installation.go
- bootstrapper/pkg/telemetry/telemetry.go
- bootstrapper/pkg/telemetry/telemetry_test.go
Related issue: https://github.com/semaphoreio/semaphore/issues/182
- Add 'Installed' state for a telemetry request
- It should only happen in bootstrapper
> feat(boostrapper): add installed telemetry request in boostrapper

- front/assets/js/workflow_editor/models/agent.js
- front/config/runtime.exs
- front/helm/templates/job-page.yaml
- front/helm/templates/project-page.yaml
- front/helm/templates/ui-cache-reactor.yaml
- front/lib/front.ex
- front/lib/front_web/templates/project/edit_workflow.html.eex
- front/lib/front_web/templates/project_onboarding/setup.html.eex
- front/lib/front_web/templates/workflow/edit.html.eex
**Fixes** https://github.com/semaphoreio/semaphore/issues/187
This PR introduces the following improvements:
- Sets the default machine type to the first available self-hosted agent type.
- Sets the default container image for promotions that use Docker environments.
- **Self-hosted agent default:**  
When adding a promotion with a block (without overriding global agent definition), the first available self-hosted agent is selected by default.  
- **Docker environment default:**  
When adding a promotion with a block that uses a Docker environment, the default container image is automatically set.
> fix(front): fix setting default agent type, image in wf editor

- ee/rbac/lib/rbac/utils/http.ex
- guard/lib/guard/utils.ex
- guard/test/guard/id/api_test.exs
- Update same_site cookie policy to Lax to prevent error 500 during login
- same_site=Lax makes the Idp always send the state cookie and it makes the auth flow to not break.
> fix(guard,rbac): Update same_site cookie policy to Lax

- github_hooks/lib/repo_host/bitbucket/payload.rb
- github_hooks/spec/lib/repo_host/bitbucket/payload_spec.rb
In really specific cases where the author is bitbucket pipelines, it will not contain a user. So the author will be:
```rb
{..., "author"=>{"raw"=>"bitbucket-pipelines <commits-noreply@bitbucket.org>", "type"=>"author"}}
```
It was breaking the parsing since the nickname would raise a MethodNotFound for nil ERROR.
> fix(github_hooks): return null if commit author is nil

- repohub/pkg/fetcher/fetcher.go
- repohub/pkg/gitrekt/errors.go
- repohub/pkg/gitrekt/update_or_clone.go
The Error() method was not implemented for custom errors in repohub, so when a caller uses it, we end up with a segfault. This fixes it by implementing that method.
> fix(repohub): implement Error() for custom errors

- front/lib/front/models/deployment_details.ex
https://github.com/renderedtext/tasks/issues/7755
How it currently looks:
How it looks after the change:
> fix(front): broken image in deployments history if user is deleted

- docs/docs/using-semaphore/optimization/container-registry.md
- docs/docs/using-semaphore/pipelines.md
- docs/package-lock.json
- docs/versioned_docs/version-CE/using-semaphore/optimization/container-registry.md
- docs/versioned_docs/version-CE/using-semaphore/pipelines.md
- docs/yarn.lock
- Add mongodb versions to Semaphore Container Registry pages
- Updated `update-browserslist-db@1.1.3` package since it was 6 months old and I got a warning
> docs: add mongodb images to registry list (Cloud and CE)

- front/assets/js/workflow_editor/editor.js
- front/config/.credo.exs
- front/lib/front/models/artifacthub.ex
- front/lib/front/models/fetching_job.ex
- front/lib/front_web/controllers/project_controller.ex
- front/lib/front_web/controllers/workflow_controller.ex
- front/lib/front_web/router.ex
- front/lib/front_web/templates/project/edit_workflow.html.eex
- front/lib/front_web/templates/workflow/edit.html.eex
- front/lib/front_web/templates/workflow/edit/frame.html.eex
- front/lib/internal_api/artifacthub.pb.ex
- front/test/front_web/controllers/project_controller_test.exs
- front/test/front_web/controllers/workflow_controller_test.exs
The workflow editor currently fetches yaml files in a synchronous call before the page is rendered, which is very unstable for large repositories and can lead to 500 errors.
This PR changes this behavior so the workflow editor starts with a zero state screen with the spinner, and the job is started in the background to fetch yaml files asynchronously. 
Once the files are fetched successfully, the workflow editor is fully rendered with visual and text editor components.
This behavior will remain behind a feature flag until we verify that it works as expected at scale.
**Note for reviewers**: 
I had to slightly increase the limit for linting the code duplication since we currently have two very similar endpoints for the workflow editor in project_controller and workflow_controller. 
An …
> feat(front): use a job to fetch yamls in workflow editor

- .semaphore/daily-builds.yml
- .semaphore/semaphore.yml
- Makefile
- artifacthub/Dockerfile
- bootstrapper/Dockerfile
- ee/velocity/Dockerfile
- encryptor/Dockerfile
- loghub2/Dockerfile
- public-api-gateway/Dockerfile
- security-toolbox/policies/docker/trivy_config.rb
- self_hosted_hub/Dockerfile
This pull request fixes a few issues that are making our daily builds fail:
- The newest version of revive requires Go 1.23, which fails the build for some applications which are still on Go 1.22 - [job](https://semaphore.semaphoreci.com/jobs/4a1e5113-c36c-45ed-9514-059510015678#L557). It's always a good practice to pin the versions of the tools used in CI, so we do that here.
- For some applications, we are not building the image before checking it with trivy, which causes the CI job to fail - [job](https://semaphore.semaphoreci.com/jobs/a23a9e73-1a76-4143-b1a4-197e778ed9b6)
- We are currently ignoring the severity in the `trivy config` command, which causes some LOW misconfigurations to fail builds. Also, those LOW misconfigurations come from Kubernetes YAMLs, which is a newer thing …
> fix(ci): pin versions of Go tools and scan only Dockerfile misconfigurations

- docs/docs/getting-started/changelog.md
- docs/docs/reference/os-apple.md
- Updated docs/docs/getting-started/changelog.md: new macos-xcode16 image was released
- Updated docs/docs/reference/os-apple.md: because macos-xcode16 image was released
> docs: update changelog

- github_hooks/db/migrate/20250409112220_add_deleted_at_for_organizations.rb
- guard/lib/guard/events/organization_deleted.ex
- guard/lib/guard/front_repo/organization.ex
- guard/lib/guard/grpc_servers/organization_server.ex
- guard/lib/guard/store/organization.ex
- guard/priv/front_repo/migrations/20250409190912_add_deleted_at_for_organizations.exs
- guard/test/guard/grpc_servers/organization_server_test.exs
- guard/test/guard/store/organization_test.exs
As a plan for making organizations restorable. We are implementing a soft-delete for them.
In another PR, a garbage collector for projects will be implemented in guard.
Main changes:
Organization GET operations only searches for orgs where deleted_at is null
Created Deleted At column to know when it was deleted for the GarbageCollector
> feat(guard): create soft delete for organizations

- repository_hub/lib/repository_hub/clients/github_client.ex
Since GitHub is now by default not allowing creation of deploy keys, we need to propagate the error that we get when Semaphore fails to create the deploy key.
Example of the error from GitHub:
```
%{"documentation_url" => "https://docs.github.com/rest/deploy-keys/deploy-keys#create-a-deploy-key", "errors" => [%{"code" => "custom", "message" => "Deploy keys are disabled for this repository", "resource" => "PublicKey"}], "message" => "Validation Failed", "status" => "422"}
```
This extracts the message from the errors list and propagates it to the user.
> fix(repository_hub): Propagate error to the user

- github_hooks/lib/internal_api/repo_proxy/branch_payload.rb
- github_hooks/lib/internal_api/repo_proxy/pr_payload.rb
- github_hooks/lib/internal_api/repo_proxy/tag_payload.rb
- github_hooks/spec/lib/internal_api/repo_proxy/branch_payload_spec.rb
- github_hooks/spec/lib/internal_api/repo_proxy/pr_payload_spec.rb
- github_hooks/spec/lib/internal_api/repo_proxy/tag_payload_spec.rb
This update enhances the payloads to include additional information required to populate `SEMAPHORE_GIT_COMMIT_AUTHOR` when a workflow is triggered via the API.
It addresses [this issue](https://github.com/renderedtext/tasks/issues/7744) and is needed for [this task](https://github.com/renderedtext/on-prem-overview/issues/235).
> fix(github_hooks): populate payloads with info about commit author

- ee/delivery-hub/pkg/grpc/actions/approve_stage_event.go
- ee/delivery-hub/pkg/grpc/actions/approve_stage_event_test.go
- ee/delivery-hub/pkg/grpc/actions/create_event_source.go
- ee/delivery-hub/pkg/grpc/actions/create_event_source_test.go
- ee/delivery-hub/pkg/grpc/actions/create_stage.go
- ee/delivery-hub/pkg/grpc/actions/create_stage_test.go
- ee/delivery-hub/pkg/grpc/actions/messages/event_source_created.go
- ee/delivery-hub/pkg/grpc/actions/messages/execution_created.go
- ee/delivery-hub/pkg/grpc/actions/messages/execution_finished.go
- ee/delivery-hub/pkg/grpc/actions/messages/execution_started.go
- ee/delivery-hub/pkg/grpc/actions/messages/message_publisher.go
- ee/delivery-hub/pkg/grpc/actions/messages/stage_created.go
- ee/delivery-hub/pkg/grpc/actions/messages/stage_event_approved.go
- ee/delivery-hub/pkg/grpc/actions/messages/stage_event_created.go
- ee/delivery-hub/pkg/grpc/actions/messages/utils.go
- ee/delivery-hub/pkg/protos/delivery/delivery.pb.go
- ee/delivery-hub/pkg/workers/pending_events_worker.go
- ee/delivery-hub/pkg/workers/pending_events_worker_test.go
- ee/delivery-hub/pkg/workers/pending_executions_worker.go
- ee/delivery-hub/pkg/workers/pending_executions_worker_test.go
- ee/delivery-hub/pkg/workers/pending_stage_events_worker.go
- ee/delivery-hub/pkg/workers/pending_stage_events_worker_test.go
- ee/delivery-hub/pkg/workers/pipeline_done_consumer.go
- ee/delivery-hub/pkg/workers/pipeline_done_consumer_test.go
- ee/delivery-hub/test/test_consumer/test_consumer.go
- Created RabbitMQ events for:
- stage created
- event source created
- stage event created (event enqueued on stage)
- stage event approved
- execution created
- execution started
- execution finished
Note: The routing key depends on pointing directly to each parent resource Id to make the available filtering in the UI
> feat(deliveryhub): implement RabbitMQ events

- Makefile
When there are multiple branches having the same tag, every make command will fail because the Docker image will have an unsupported format
> fix: If there are multiple branches having current tag, use the first one

- public-api/v1alpha/Dockerfile
Alpine 3.18 has reached [EOL](https://endoflife.date/alpine-linux)
> toil(api/v1alpha): update outdated alpine image

- statsd/Dockerfile
Alpine 3.18 has reached [EOL](https://endoflife.date/alpine-linux)
> toil(statsd): update outdated alpine image

- github_hooks/Gemfile.lock
Alpine 3.18 has reached [EOL](https://endoflife.date/alpine-linux)
> toil(github_hooks): update outdated alpine image

- secrethub/Dockerfile
Alpine 3.18 has reached [EOL](https://endoflife.date/alpine-linux)
> toil(secrethub): update outdated alpine image

- repository_hub/lib/repository_hub/clients/bitbucket_client.ex
This PR fixes how we're sending status checks to Bitbucket. 
When a project uses [block-level](https://docs.semaphoreci.com/using-semaphore/projects#edit-status-checks) status checks, the repository hub assumes it's always a pipeline status. 
We fixed this using the same data we have for GitHub status checks.
> fix(repositoryhub): bitbucket status checks for blocks

- Makefile
- docs/docs/reference/openid.md
- secrethub/Makefile
- secrethub/lib/internal_api/secrethub.pb.ex
- secrethub/lib/secrethub/open_id_connect/jwt.ex
- secrethub/lib/secrethub/open_id_connect/jwt_claim.ex
- secrethub/lib/secrethub/open_id_connect/jwt_configuration.ex
- secrethub/test/secrethub/internal_grpc_api_test.exs
- secrethub/test/secrethub/open_id_connect/jwt_configuration_test.exs
- zebra/Makefile
- zebra/lib/protos/internal_api/secrethub.pb.ex
- zebra/lib/zebra/workers/job_request_factory.ex
- zebra/lib/zebra/workers/job_request_factory/open_id_connect.ex
Adds `prj` (project name) and `org` (organization name) claims to the OIDC token. More in the [public discussion](https://github.com/semaphoreio/semaphore/issues/204).
See also [this task](https://github.com/renderedtext/tasks/issues/7975).
> feat(secrethub): add project and org. name to OIDC token claims

- front/lib/front_web/views/deployments_view.ex
- Plumber pipeline status are CANCELED instead of CANCELLED
- This was causing some issues in the deployment status history page icons
> fix(front): wrong pipeline mapping in deployment targets

- front/Dockerfile
- front/helm/templates/job-page.yaml
- front/helm/templates/project-page.yaml
- front/helm/templates/ui-cache-reactor.yaml
- helm-chart/values.yaml.in
These changes improve the local development experience when running the cluster locally by enabling file syncing and automatic server restarts. They address local compatibility issues and allow runtime file writes inside pods still running under MIX_ENV=prod.
- Replaced custom Node Dockerfile stage with node:16-alpine to fix local build issues.
- Added `entr` for watching file changes during development.
- Changed CMD to restart Phoenix server using `entr` on source file updates.
- Made `readOnlyRootFilesystem` configurable based on the new flag.
> feat(front): enable writable root FS and live reload for front

- guard/lib/guard/api/project.ex
- Add correct owner filter for list projects by owner besides user_id
- Instead of getting project owner projects, it was getting all projects related to the user, blocking the deletion of the user by the API, independent of how many projects he has
- Since our tests are mocking this response, it was not able to test its correctness
> fix(guard): add correct owner filter for list projects by owner

- docs/docs/reference/env-vars.md
- plumber/ppl/lib/ppl/definition_reviser/blocks_reviser.ex
- plumber/ppl/test/definition_reviser/blocks_reviser_test.exs
- plumber/ppl/test/ppl_blocks/stm_handler/run_test.exs
- plumber/ppl/test/ppl_sub_inits/stm_handler/compilation/definition_test.exs
Adding SEMAPHORE_BLOCK_NAME env variable to jobs. This will allow showing better metrics about jobs on a workflow.
> feat(plumber): inject SEMAPHORE_BLOCK_NAME env to jobs

- zebra/lib/zebra/apis/internal_task_api/schedule.ex
- zebra/test/support/stubbed_provider.ex
- zebra/test/zebra/apis/internal_task_api/schedule_test.exs
- zebra/test/zebra/workers/feature_provider_invalidator_worker_test.exs
Makes max job execution time limit configurable via feature flag.
> feat(zebra): Configure max job time limit based on a feature flag

- front/assets/js/report/index.tsx
Right now, the mermaid charts are being initialized on the page load. 
This can cause issues(charts not getting rendered) when the DOM is not yet ready. 
This PR fixes this issue.
> fix(front): wait for markdown before rendering it

- public-api/v1alpha/lib/pipelines_api/workflow_client/wf_request_formatter.ex
- public-api/v1alpha/test/workflow_client_test.exs
In the recent changes to how the Run workflow API works in the backend, we changed by mistake the expected name for the parameter that holds the name of the pipeline file. This PR fixes that issue and adds a test to verify that the request is properly formed based on the input parameters.
> fix(api v1alpha): Use pipeline_file as param name in Run wf API

- plumber/block/priv/repos/22_skip_block/.semaphore/skip_block_with_failed_job.yml
- plumber/ppl/lib/ppl/ppl_blocks/stm_handler/initializing_state.ex
- plumber/ppl/test/grpc/server_test.exs
When performing a partial rebuild, skipped blocks from the original pipeline caused the system to get stuck because:
1. **Skipped blocks have `block_id: nil`**  
They never get scheduled in the Block service.
2. **Pattern matching issue**  
The existing code only matched `%{state: "done", result: "passed"}` without considering `result_reason: "skipped"`.
3. **`Block.duplicate` failure**  
The code called `Block.duplicate(nil, new_ppl_id)` which failed because:
- `BlockRequestsQueries.get(nil)` returns `nil`
- No `BlockRequest` exists to duplicate
- Block gets stuck in `initializing` state instead of `done/passed/skipped`
---
1. **Specific Pattern Match**  
Matches exactly the skipped block signature:
- `block_id: nil` (never scheduled)
- `state: "done"` (completed)
- `result: "passed"` …
> fix(plumber): handle skipped blocks in partial pipeline rebuilds

- public-api-gateway/helm/templates/dpl.yaml
Service is using rabbitmq but is missing init container that waits for rabbitmq pod bootup
> fix(public-api-gateway): add missing rabbitmq init container

- bootstrapper/Dockerfile
- bootstrapper/go.mod
- bootstrapper/go.sum
- Fixes CVE-2025-22868
- Bumps golang to 1.23
> toil(bootstrapper): fix CVE-2025-22868, bump go to 1.23

- front/assets/css/main.css
- front/assets/js/dashboard/interval_selector.js
- front/assets/js/deployments/components/subjects.js
- front/assets/js/deployments/history_page.js
- front/assets/js/flaky_tests/components/disruption_history_chart.tsx
- front/assets/js/flaky_tests/components/history_chart.tsx
- front/assets/js/flaky_tests/components/top_flaky_charts.tsx
- front/assets/js/flaky_tests/pages/flaky_tests_page.tsx
- front/assets/js/insights/components/custom_dashboards.tsx
- front/assets/js/insights/components/dashboard_item_card.tsx
- front/assets/js/insights/components/navigation.tsx
- front/assets/js/manage_secret.js
- front/assets/js/pre_flight_checks/secrets.js
- front/assets/js/report/index.tsx
- front/assets/js/tasks/history_page.js
- front/assets/js/tippy.js
- front/lib/front_web/templates/error/404.html.eex
- front/lib/front_web/templates/error/500.html.eex
The current CSS processing pipeline does not support loading CSS styles from JavaScript. Because of this, we've moved loading styles from JS files to the `main.css` file.
> fix(front): move css loading from js => css

- front/lib/front_web/controllers/test_results_controller.ex
> toil(front): ensure resource ownership match for test results

- repository_hub/lib/repository_hub/clients/gitlab_client.ex
Branch and tag names containing forward slashes (e.g., "feature/branch-name", "release/v1.0.0") were causing 404 errors when making API requests to GitLab. Added URI.encode with char_unreserved predicate to properly encode special characters in names according to RFC 3986.
> fix(repository_hub): URL encode branch and tag names for GitLab API

- guard/lib/guard/front_repo/user.ex
- guard/lib/guard/store/service_account.ex
- guard/test/guard/grpc_servers/user_server_test.exs
- guard/test/guard/service_account/actions_test.exs
- guard/test/guard/store/service_account_test.exs
- guard/test/guard/user/actions_test.exs
- guard/test/support/factories/service_account_factory.ex
There's a problem in `guard` service causing service account email addresses to be generated improperly: test-sas@service-accounts.unknown.semaphoreci.com instead of picking the organization username, the default `unknown` name is selected. Because of this, creating a service account with a name that was already used by a different organization - fails. 
In addition, we're renaming part of the service account email suffix from `service_accounts` to `service-accounts`.
> fix(guard): use correct field for generating service account email domains

- zebra/lib/zebra/workers/job_request_factory/cache.ex
Job for fetching yaml files for workflow editor was stuck in queueing state as `repo_proxy` is `nil`, broken in this PR: https://github.com/semaphoreio/semaphore/pull/480
Change was tested on preprod env
> fix(zebra): workflow editor job not working because of forked_pr evaluation

- auth/lib/auth/ip_filter.ex
- auth/test/auth/ip_filter_test.exs
To strengthen the security of the application, we are going to block connections when we are not able to detect the remote IP, and the organization is using an allow IP list.
> feat(auth): block connection in case of invalid request ip

- front/assets/js/flaky_tests/components/actions.tsx
https://github.com/renderedtext/project-tasks/issues/2741
> HTML sanitize test reports

- front/assets/css/app-semaphore.css
- front/assets/js/tasks/components/target.js
- front/assets/js/tasks/index.js
- front/assets/js/tasks/just_run_form.js
- front/assets/js/workflow_view/switch.js
- front/assets/js/workflow_view/target_params.js
- front/lib/front/models/scheduler.ex
- front/lib/front_web/controllers/schedulers_controller.ex
- front/lib/front_web/templates/schedulers/_trigger.html.eex
- front/lib/front_web/templates/schedulers/forms/_target.html.eex
- front/lib/front_web/templates/schedulers/run.html.eex
- front/lib/front_web/templates/schedulers/tasks/details.html.eex
- front/lib/front_web/templates/schedulers/tasks/header.html.eex
- front/lib/front_web/views/schedulers_view.ex
- front/lib/internal_api/periodic_scheduler.pb.ex
- front/test/front/models/scheduler_test.exs
- front/test/front_web/controllers/schedulers_controller_test.exs
- front/test/support/stubs/db.ex
- front/test/support/stubs/scheduler.ex
- Small improvement: search dropdown on `run_now` page if parameter has more than 10 possible values
- Support for tags on schedulers/tasks
- protobuf refresh
- DB stub update fixes flaky browser tests in promotions:
- [test when deployment targets are enabled when target has deployment target that blocks promotion
](https://semaphore.semaphoreci.com/projects/semaphore/flaky_tests/028249c9-90ad-38c3-9fa3-55ddf43195c1)
- [test when deployment targets are enabled when target has deployment target that allows promotion](https://semaphore.semaphoreci.com/projects/semaphore/flaky_tests/3c1225ae-7037-3a06-be84-47fe841887fc)
> feat(front): Support tags for tasks and task just run

- public-api/v1alpha/lib/pipelines_api/schedules/run_now.ex
- public-api/v1alpha/test/router/schedules/run_now_test.exs
> fix(public-api/v1alpha): run_now allowed without branch and reference  fields

- public-api/v1alpha/lib/pipelines_api/periodic_scheduler_client/request_fromatter.ex
- public-api/v1alpha/test/periodic_scheduler_client/request_formatter_test.exs
If reference and branch are both empty in request the run_now request should also be empty
>   fix(public-api/v1alpha): handle empty reference fields correctly

- zebra/lib/zebra/monitor.ex
The `stuck_jobs` query was updated to only include jobs started within the last 7 days. This prevents stale jobs from accumulating in the metric and triggering false alarms, making the metric more accurate for real time monitoring.
More in [this issue](https://github.com/renderedtext/tasks/issues/8656).
> metrics(zebra): add 7-day filter to stuck jobs query

- front/assets/js/report/index.tsx
Default sandboxing provided by mermaid-js is not compatible with our CSPs since it uses src=`data:...`  to forward the content that should be rendered in the iframe, so we're falling back to `secure`.
> fix(front): Remove mermaid sandboxing as it conflicts with csp

- front/lib/front/models/workflow.ex
- front/lib/front/workflow_page/pipeline_status/model.ex
> feat(front): add finite cache ttl for running pipelines
